name: Release

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies to build application
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libsystemd-dev gcc-aarch64-linux-gnu
      - name: Run releaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
